### ISSUE TITLE
100% d'import failed

### ISSUE THREAD

**Issue by parigi-n** [mukurokudo/imdb2senscritique#1]
Salut,

J'ai testé par curiosité le script avec mon nouveau compte, et aucune des importations IMDB ont marché.
Le script est allé au bout et à lu les 124 lignes, par contre, elles ont toutes "failed".

Peut-etre que c'est du au fait que je l'ai testé avec PHP 7 ? (qui est un peu la base de php en 2016 quand même)
Ou alors c'est due au fait c'est un compte relativement récent ?

**Comment by mukurokudo** [comment]
Si le nombre de ligne traitées s'est affiché, l'appel CURL de connexion et le parcours du fichier csv se sont éxecutés sans problèmes. Le problème se situe à la reconnaissance du film par son titre. Peux tu uploader une ligne d'exemple de ton csv et/ou tester avec le csv d'exemple?

**Comment by parigi-n** [comment]
Voila mon .csv (je suis obligé de le mettre dans un .zip sinon Github veut pas que je l'upload).
Je vais tester avec le tien aussi.

[WATCHLIST.zip](https://github.com/mukurokudo/imdb2senscritique/files/428419/WATCHLIST.zip)

**Comment by mukurokudo** [comment]
Ok je pense voir d'où vient le problème. Ton export csv est en français et à la ligne 57 du script, je compare le titre du film avec le titre original.
Il faudrait donc changer la ligne 

``` php
$thisOriginalTitle = (isset($thisMovieRaw->find('p.elco-original-title',0)->plaintext)?$thisMovieRaw->find('p.elco-original-title',0)->plaintext:null);
```

par

``` php
$thisOriginalTitle = (isset($thisMovieRaw->find('a.elco-anchor',0)->plaintext)?$thisMovieRaw->find('a.elco-anchor',0)->plaintext:null);
```

Je ferai un paramètre plus tard.
Je viens également de remarquer que le titre original n'est pas renseigné sur senscritique ce qui faisait échouer l'import de certaines lignes. Là aussi je ferai un fix plus tard.

J'espère que ça résoudra ton problème.

**Comment by parigi-n** [comment]
Ok deja en exportant le csv en anglais et sans ton fix, j'en suis à 1/3 de updated. C'est deja mieux !
En anglais avec le fix, je tourne à 100% de failed (logique)
Mais en français avec le fix, je suis toujours à 100% de failed.

Merci en tout cas !

EDIT: le 
[exempleFile.zip](https://github.com/mukurokudo/imdb2senscritique/files/428458/exempleFile.zip)
csv en anglais
