### ISSUE TITLE
301 error

### ISSUE THREAD

**Issue by nliautaud** [mukurokudo/imdb2senscritique#2]
Hi,
I have a 301 server error at SC connection.
Do you know if there was an URI change (site login requests are still going to `/sc2/auth/login.json` thus) or maybe something wrong with the headers ?

**Comment by mukurokudo** [comment]
It seems they have change the protocol to https. I have commited a change but I didn't have time to test. Can you try it and tell me if it's working again?
Thanks

**Comment by nliautaud** [comment]
I totally missed that. Well done, it's working.
